### ISSUE TITLE
custom data

### ISSUE THREAD

**Issue by drewskidang** [run-llama/sec-insights#12]
I saw the youtube video that allowed for custom data but is possible to still use the UI with custom data. I want to legal docs instead of sec filings

**Comment by sourabhdesai** [comment]
Hi @drewskidang , thanks for checking out the project and for watching the video!

Our frontend is pretty tightly coupled to the SEC filings use case at the moment :/ the `make chat` CLI tool exists as a workaround for this for now. Don't think we have plans to make the frontend more flexible for custom docs

I think most of the refactoring work would be on the Landing page. The actual chat page may be pretty flexible already aside from the PDF sidebar tabs that shows the SEC document titles. Hope that helps if you want to consider making those changes on your fork *(and possibly contributing back to this repo! 🙂 )*

**Comment by drewskidang** [comment]
I will try !

**Comment by sourabhdesai** [comment]
Closing the issue as it seems to be resolved. Please re-open if you continue having an issue related to this!
