### ISSUE TITLE
Issues setting up backend section of readme

### ISSUE THREAD

**Issue by chiragshah285** [run-llama/sec-insights#2]
Getting the error below when running the `docker compose up`:

```
backend-llama-app-fastapi-1  | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
backend-llama-app-fastapi-1  |  Is the server running on host "127.0.0.1" and accepting
backend-llama-app-fastapi-1  |  TCP/IP connections on port 5432?
backend-llama-app-fastapi-1  | 
backend-llama-app-fastapi-1  | (Background on this error at: https://sqlalche.me/e/20/e3q8)
backend-llama-app-fastapi-1  | 
backend-llama-app-fastapi-1  | ERROR:    Application startup failed. Exiting.
```

This was part of step 6 in the backend/ReadMe file. Am I missing something?

**Comment by sourabhdesai** [comment]
@chiragshah285 thanks for flagging this! There may be somewhat of a race condition between the start of the FastAPI service and the postgres DB. Do you still get the error if you start the db first with `docker compose start db` and then the Fast API service with `docker compose start llama-app-fastapi`?

May also be easier to just use `make run` which spins up the DB & LocalStack in their docker containers and the API service on your own OS without docker.

**Comment by chiragshah285** [comment]
thanks @sourabhdesai those two commands `docker compose start db ``docker compose start llama-app-fastapi` work sequentially perfectly fine! 

When I run `make run`: I get the error below
```
(llama-app-backend-py3.10) (base) chiragshah@Chirag-Shah-MBP backend % make run
echo "Running in local mode."
Running in local mode.
docker compose start db
docker compose start localstack
[+] Running 1/1
 ✔ Container localstack_main  Started                                                                                                                                                                                 0.7s 
poetry run start
Running in AppEnvironment: local
2023-09-05 18:01:28,714 [MainThread  ] [INFO ]  Set up logging with log level 10
2023-09-05 18:01:28,714 [MainThread  ] [INFO ]  Skipping Sentry setup
2023-09-05 18:01:28,714 [MainThread  ] [DEBUG]  Skipping migrations
INFO:     Will watch for changes in these directories: ['/Users/chiragshah/PycharmProjects/sec-insights/backend']
ERROR:    [Errno 48] Address already in use
make: *** [run] Error 1
```

**Comment by sourabhdesai** [comment]
Glad to hear it! Let us know if you run into any other issues

**Comment by cosminro** [comment]
For me it doesn't work if I run the two sequentially
docker compose start db ``docker compose start llama-app-fastapi
the start command just swallows the error and hangs

if I try docker compose up llama-app-fastapi I can see the same erorr reported at the top
