### ISSUE TITLE
ERROR:    [Errno 48] Address already in use

### ISSUE THREAD

**Issue by 345ishaan** [run-llama/sec-insights#21]
While running `make run` to launch the backend server, i am frequently seeing this error. I checked if other background processes and also change the port in `.env` but neither worked. any suggestions?

**Comment by siddarthreddygsr** [comment]
can you share the output of ` sudo netstat -tulpn | grep LISTEN `

**Comment by JeroenJADS** [comment]
I had this as well, but asking netstat which process listened on port 8000 and closing that one worked.

**Comment by sourabhdesai** [comment]
+1 to what @siddarthreddygsr and @JeroenJADS said. Also, if you previously tried starting the service with `docker compose up`, you may want to check if the `llama-app-fastapi` container is still active. If so, you can stop it with `docker compose stop llama-app-fastapi`

**Comment by sourabhdesai** [comment]
Closing the issue as there's no follow-up. Please re-open if you continue having an issue related to this!

**Comment by 345ishaan** [comment]
Thanks for the suggestions. I was able to solve it by stopping the docker container via Docker-Desktop app.
