### ISSUE TITLE
How to make my own QA application

### ISSUE THREAD

**Issue by yinheng-gh** [run-llama/sec-insights#3]
Hi,
First of all, thank you for creating such a great QA application. 
I have a question (or rather a requirement): If I don't want to use it to analyze SEC data, but instead want to import and analyze my own PDF files to create my own knowledge based QA application, where can I make the simplest modifications? Thank you.

**Comment by sourabhdesai** [comment]
Hi @yinheng-gh, great question!

We're actually working on a tutorial for our [YouTube channel](https://www.youtube.com/@LlamaIndex) where we will discuss how to do this. That video should be out soon! In the meantime, you can see that our [`Document`](https://github.com/run-llama/sec-insights/blob/main/backend/app/models/db.py#L41-L49) table is defined to be fairly generic. As long as you can insert a row into your document table with a valid link pointing to a PDF file, you should be able to run [the seed script](https://github.com/run-llama/sec-insights/tree/main/backend#seed-db-script-) to process the PDF and then start chatting with it using the [chat script](https://github.com/run-llama/sec-insights/tree/main/backend#chat-) (`make chat`).

**Comment by yinheng-gh** [comment]
Really appreciate it, thanks!

**Comment by sourabhdesai** [comment]
@yinheng-gh FYI we just posted the YouTube video this morning and there's a section [here](https://youtu.be/2O52Tfj79T4?si=jkGsn9KYiydNcwlK&t=1311) for using custom documents!
