### ISSUE TITLE
I got error on the UI side

### ISSUE THREAD

**Issue by kikirizki** [run-llama/sec-insights#33]
Hi thank you so much for your great work, but I got error  Server: "react-select-4-live-region" Client: "react-select-3-live-region"

**Comment by kikirizki** [comment]
![could not fetch](https://github.com/run-llama/sec-insights/assets/7989381/41babe34-13fd-423b-bad8-f68ee1d66b9d)

**Comment by kikirizki** [comment]
@sourabhdesai thank you for your response
this is the full error 
`Warning: Prop `aria-controls` did not match. Server: "downshift-2-menu" Client: "downshift-1-menu"
input
div
div
div
DocumentSelectCombobox@webpack-internal:///./src/components/landing-page/SelectTicker.tsx:28:104
div
div
div
div
TitleAndDropdown@webpack-internal:///./src/components/landing-page/TitleAndDropdown.tsx:44:74
LandingPage
Layout@webpack-internal:///./src/components/Layout.tsx:9:25
le@webpack-internal:///./node_modules/react-use-intercom/dist/index.mjs:9:2905
MyApp@webpack-internal:///./src/pages/_app.tsx:18:38
PathnameContextProviderAdapter@webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:74:44
ErrorBoundary@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:305:63
ReactDevOverlay@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:854:908
Container@webpack-internal:///./node_modules/next/dist/client/index.js:77:1
AppContainer@webpack-internal:///./node_modules/next/dist/client/index.js:206:25
Root@webpack-internal:///./node_modules/next/dist/client/index.js:384:37 

See more info here: https://nextjs.org/docs/messages/react-hydration-error client.js:1:909
`

`could not fetch documents client.js:1:909
    error client.js:1
    error next-dev.js:27
    instrumentConsole instrument.js:111
    useDocumentSelector useDocumentSelector.tsx:42
    (Async: promise callback)
    useDocumentSelector useDocumentSelector.tsx:42
    React 7
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    (Async: EventHandlerNonNull)
    <anonymous> scheduler.development.js:571
    <anonymous> scheduler.development.js:633
    NextJS 4
    <anonymous> index.js:6
    NextJS 4
    React 2
    NextJS 4
    <anonymous> React
    NextJS 4
    <anonymous> React
    NextJS 4
    <anonymous> index.js:38
    NextJS 4
    <anonymous> next-dev.js:7
    NextJS 7
`

the backend does not seem to receive any request
fyi: I use localstack

**Comment by kikirizki** [comment]
@sourabhdesai I also tried to run both front end and back end on codespace on got error during, when accessing
base_url/conversation/[conversation id], please check the following error 
![conversation](https://github.com/run-llama/sec-insights/assets/7989381/0129551d-0050-46d2-b0bf-2faf23bde266)
is this related to the use of localstack ?

**Comment by sourabhdesai** [comment]
@kikirizki I think the error above this that says `"Conversation Load Error"` would have some more helpful information. It's likely that there's an issue with the CORS configuration on the backend that's blocking the frontend from completing its requests.

**Comment by sourabhdesai** [comment]
Closing since there aren't any further questions.

**Comment by git-shogg** [comment]
Hi @sourabhdesai, amazing work with this project and thank you so much for sharing! I have also come across the same issue mentioned above with codespaces. I figure it must be something minor I have missed. Wondering if it is something to do with CORS? When you run this in codespaces do you make any other adjustments to env files before start up (other than the OPENAI API)? 
I have tried changing a couple of other variables mentioned below but still no luck (not 100% sure if required):
- Tried changing the `NEXT_PUBLIC_BACKEND_URL` variable in the frontend env file from `http://localhost:8000/` to point to the specific instance of the running codespace on 8000. 
- Tried updating the backend env file `BACKEND_CORS_ORIGINS` variable to point to the specific instance of the running codespace.

Thanks again!

P.S. @kikirizki  did you happen to fix this?

**Comment by kikirizki** [comment]
Hi @git-shogg I am sorry for late reply, yes I managed to fix it, but I did not fully recall what change I made nor I commit the change to github, 
but here are my suggestion there were some hard-coded variable in the bash script or python script (idk if it still there) related to some urls, please check them and made adjustment accordingly
