### ISSUE TITLE
role "user" does not exist when running make migrate

### ISSUE THREAD

**Issue by brendankmorrison** [run-llama/sec-insights#34]
make run_docker seemed to work but I ran into this error when running make migrate.

**Comment by sourabhdesai** [comment]
@brendankmorrison still having issues with this? May be worth just tearing down your postgres container and re-creating it. You'd need to run `docker volume ls` and then `docker volume rm <postgres volume name>`.

**Comment by sourabhdesai** [comment]
FWIW, I've since added a [`make refresh_db` command](https://github.com/run-llama/sec-insights/blob/main/backend/Makefile#L19) to the  `backend/Makefile` which may come in handy for this as well.

Closing since there aren't any further questions.
