### ISSUE TITLE
Can we integrate the same solution with text2sql instead of pdf document

### ISSUE THREAD

**Issue by byamasu-patrick** [run-llama/sec-insights#42]
This template currently focuses solely on using it for conversations with documents in PDF format. However, since the majority of enterprise data is structured, could we also consider supporting a text-to-SQL use case? In this scenario, rather than uploading two separate documents, users could opt to upload only one document and select specific tables they wish to interact with for data analysis. They could then use the document to augment the knowledge, facilitating the creation of more robust completions. If someone want to use this how we can approach this idea? I have tried it but seems like am not able to reach to the actual goal. @sourabhdesai , @antimatter15 @kikirizki @eltociear @siddarthreddygsr do you have any idea on how to approach this?

**Comment by sourabhdesai** [comment]
@byamasu-patrick sounds like we got this sorted out in discord right? [Message link](https://discord.com/channels/1059199217496772688/1150942525968879636/1156994141817942117)

Closing but re-open if I'm mistaken.
