### ISSUE TITLE
if it's possible to use Minio instead of S3 buckets. If so, could you please advise me on what changes are required to make that switch?

### ISSUE THREAD

**Issue by DhananjayanOnline** [run-llama/sec-insights#59]

**Comment by sourabhdesai** [comment]
@DhananjayanOnline good question. Luckily, much of the way the LlamaIndex framework itself interacts with S3 is via [`s3fs`](https://s3fs.readthedocs.io/en/latest/) here in [engine.py](https://github.com/run-llama/sec-insights/blob/main/backend/app/chat/engine.py#L66-L74). Looks like `s3fs` does in fact claim to have some level of support for MinIO [here](https://s3fs.readthedocs.io/en/latest/#s3-compatible-storage). Would be great if you could try that out and report back on how it goes!
