### ISSUE TITLE
Issues with upsert new docs

### ISSUE THREAD

**Issue by shotyme** [run-llama/sec-insights#63]
Hi, after following your tutorial the app is running correctly and I was trying to insert some docs via the upsert_document.py script. But I'm getting a lot of errors which indicates that the dependencies are are not resolved correctly (module Fire could not be found)

I'm using codespaces and installed the dependencies via poetry install
What am I missing here?

**Comment by DhananjayanOnline** [comment]
@shotyme  Please activate the poetry shell and then reattempt the command.
