### ISSUE TITLE
AttributeError: 'CustomPGVectorStore' object has no attribute '_async_session'

### ISSUE THREAD

**Issue by shavejshaikh** [run-llama/sec-insights#72]
![image](https://github.com/run-llama/sec-insights/assets/43640329/756d88e9-5a16-4387-8477-e3a8558d92b9)

While running a application getting attributeError

After set the value of _async_session getting below error
![image](https://github.com/run-llama/sec-insights/assets/43640329/2acabde5-8f8d-41fc-9389-491c86b1d461)

**Comment by sourabhdesai** [comment]
@shavejshaikh I think you just need to update your fork to the latest code in this main repo. Your stacktrace shows the error coming from `async with self._async_session() as session:` on line 43 of `pg_vector.py`. As you can see in the latest code [here](https://github.com/run-llama/sec-insights/blob/d7110150a91d6399c6ccb2dd19913b826fd7be68/backend/app/chat/pg_vector.py#L43), we've since added a call to `self._initialize()` that sets up these session variables. Let me know if that fixes your error!

**Comment by shavejshaikh** [comment]
@sourabhdesai  While migrating using `make migrate` getting error 
![image](https://github.com/run-llama/sec-insights/assets/43640329/203033ea-8841-4f83-a8a8-6964592e1873)

**Comment by shavejshaikh** [comment]
@sourabhdesai  After cloning latest code again getting error while migrating 
![image](https://github.com/run-llama/sec-insights/assets/43640329/38e41de0-6500-4dd4-bfc1-b18b87eda9f2)
Any idea ?

**Comment by shavejshaikh** [comment]
@sourabhdesai After update `pg_vector.py `getting error 
`AttributeError: 'CustomPGVectorStore' object has no attribute '_initialize'
`![image](https://github.com/run-llama/sec-insights/assets/43640329/0add95f2-6458-4d0e-99ac-94fd07da4b66)

**Comment by shavejshaikh** [comment]
@sourabhdesai , now getting DETAIL:  Could not open extension control file "/usr/share/postgresql/16/extension/vector.control": No such file or directory.
Created env using conda and install dependency using poetry
![image](https://github.com/run-llama/sec-insights/assets/43640329/98261b6a-dbf8-4e17-b40f-5efb757a6b53)

Any idea ?

**Comment by shavejshaikh** [comment]
Found the solution since pgvector isn't install along with postgres (Ubuntu).
1. Check postgres version
`postgres=# SHOW SERVER_VERSION;
`
![image](https://github.com/run-llama/sec-insights/assets/43640329/37c6dac9-7039-4eb3-89a9-71ad0bdd9845)

2. Install pgvector based on above postgres version
`sudo apt install postgresql-16-pgvector
`
Change 16 based on your postgres version
