### ISSUE TITLE
Make migration

### ISSUE THREAD

**Issue by rohit-1906** [run-llama/sec-insights#76]
poetry run python -m alembic upgrade head
/root/.cache/pypoetry/virtualenvs/llama-app-backend--Qk0ygDj-py3.11/bin/python: No module named alembic.__main__; 'alembic' is a package and cannot be directly executed
make: *** [Makefile:15: migrate] Error 1

**Comment by sourabhdesai** [comment]
closing as duplicate of [this](https://github.com/run-llama/sec-insights/issues/77#issue-1998747319)
