### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by hollowman010** [run-llama/sec-insights#86]
Hi Sourab,
For some reason the program is unable to establish connection.  I tried to change the port, but that didnt work. I can see the document in the bucket (https://investors.mongodb.com/static-files/10f57c7a-a481-4663-bbc5-1cc79e36b147). Curious what am I missing? Yesterday it worked just fine. Thanks for the help.
<img width="1213" alt="Screenshot 2024-01-06 at 9 39 01 AM" src="https://github.com/run-llama/sec-insights/assets/153334817/45b2e9d0-2146-4670-a6be-b8be18fb6b7b">

**Comment by hollowman010** [comment]
I was able to get it running, however, I am unable to get any output from the document:
 
<img width="1959" alt="Screenshot 2024-01-06 at 10 30 05 AM" src="https://github.com/run-llama/sec-insights/assets/153334817/dc9950d0-e8bb-4852-81cf-aa23aead5139">

<img width="1608" alt="Screenshot 2024-01-06 at 10 30 19 AM" src="https://github.com/run-llama/sec-insights/assets/153334817/2e48f883-1be7-453b-855d-63dd6fc1e7c0">

<img width="1939" alt="Screenshot 2024-01-06 at 10 30 30 AM" src="https://github.com/run-llama/sec-insights/assets/153334817/15022b18-0aba-4a35-89a7-095dd06ed811">

**Comment by PapaRedNinjago** [comment]
if you are running from Codespace, have you tried make your port public?
