### ISSUE TITLE
Query on Custom SEC filings via UI

### ISSUE THREAD

**Issue by deepak590** [run-llama/sec-insights#9]
Hello @sourabhdesai, First off, thank you for your contribution to the community. This project is truly awesome.

I was exploring the live UI and noticed that it features filings for a select group of companies. I want to know if it is possible to locally deploy an app that can answer queries for other SEC filings.

I understand from looking at the code that the backend might be equipped to handle this, but I'm unclear on whether the front end supports this feature or not. If it's not already implemented, do you think it's feasible to run the app locally and tailor it for the filings of different companies?

Would appreciate your insights. Looking forward to hearing from you!

**Comment by sourabhdesai** [comment]
Hi @deepak590, thanks for checking out the repo!

Yes you can do this by using our [seed script](https://github.com/run-llama/sec-insights/tree/main/backend#seed-db-script-)!

You can run the seed script with the `--ciks` CLI arg *(e.g. `python scripts/seed_db.py --ciks '["1640147"]'`)*. The `ciks` arg allows you to define which companies you want to download SEC filings for. You can search for the CIK value for a given company using the SECs search tool on [this website](https://www.sec.gov/edgar/searchedgar/companysearch).

Alternatively, you may also just add the CIKs you want to include in your project by modifying the `DEFAULT_CIKS` list [here](https://github.com/run-llama/sec-insights/blob/main/backend/scripts/download_sec_pdf.py#L12).

Just make sure you follow the setup instructions as a pre-requisite to running the seed script :)

Will make a mental note to myself to add this question to the FAQ document I'm adding soon!

**Comment by sourabhdesai** [comment]
Closing the issue as it seems to be resolved. Please re-open if you continue having an issue related to this!
